# Generated by Django 5.0.2 on 2025-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_eventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='eventos',
            name='cupo_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='programa_educativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(default='Nombre genérico', max_length=255),
        ),
    ]
