# Generated by Django 5.0.2 on 2025-05-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0005_remove_eventos_fecha_fin_remove_eventos_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='es_publico',
        ),
        migrations.AddField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
