# Generated by Django 5.0.2 on 2025-05-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_remove_eventos_es_publico_eventos_publico_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
